spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/freepdb1
    username: mlops
    password: mlops
  ai:
  vectorstore:
    oracle:
    index-type: IVF
    distance-type: COSINE
    dimensions: 65535